send_command:
  description: Send a command to a Tuya IR AC device
  fields:
    entity_id:
      description: Entity ID of the Tuya IR AC device
      example: 'climate.living_room_ac'
      required: true
    command:
      description: Command to send (e.g., 'turn_on', 'turn_off')
      example: 'turn_on'
      required: true
